### ISSUE TITLE
React⇒Next移行にて、Dcokerビルドがエラーになる件

### ISSUE THREAD

**Issue by tokaisagami** [tokaisagami/nightmare-app-next#2]
お世話になっております。
以下、今回発生しているエラー内容です。
お忙しいところ恐縮ですが、ご確認お願い致します。

## 解決したいこと・達成したいものについて
元々フロントをReact.jsで作成したのですが、本リリースにあたり、管理のしやすさや今後の就活での有効性を考えて、Next.jsで作成しなおそうと考え、移行を実施しております。

## 聞きたいこと・アドバイスが欲しいこと
Next.jsで新しいフロント用のプロジェクトを立ち上げ、Next.js仕様に各ファイルの記述や配置などを変更したのですが、Dockerビルドを実行すると、プリレンダリング時に必ずエラーが発生してしまいます。
以下のエラー内容について、解消方法やアドバイスをいただきたく存じます。
  
エラー内容
（下記では"/mypage"でエラー発生とありますが、ビルドを繰り返すごとに"/modified-nightmare"など別のディレクトリでもエラーが発生しているように表示されることがあります）
```
 => ERROR [frontend 6/6] RUN npm run build                                                                        50.1s
------
 > [frontend 6/6] RUN npm run build:
2.330
2.330 > nightmare-app-next@0.1.0 build
2.330 > next build
2.330
3.811 Attention: Next.js now collects completely anonymous telemetry regarding usage.
3.811 This information is used to shape Next.js' roadmap and prioritize features.
3.811 You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
3.811 https://nextjs.org/telemetry
3.811
3.956    ▲ Next.js 15.1.0
3.956    - Environments: .env
3.956
4.085    Creating an optimized production build ...
27.81  ✓ Compiled successfully
27.92    Linting and checking validity of types ...
42.97    Collecting page data ...
48.62    Generating static pages (0/11) ...
49.90 Error occurred prerendering page "/mypage". Read more: https://nextjs.org/docs/messages/prerender-error
49.90 Error: This function is not supported in React Server Components. Please only use this export in a Client Component.
49.90     at n (/app/.next/server/chunks/689.js:3:57876)
49.90     at ek (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:13368)
49.90     at e (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:17266)
49.90     at e$ (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:17728)
49.90     at Object.toJSON (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:14874)
49.90     at stringify (<anonymous>)
49.90     at eU (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:26231)
49.90     at eB (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:26461)
49.90     at eq (/app/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:84:27015)
49.90     at AsyncLocalStorage.run (node:async_hooks:338:14)
49.90 Export encountered an error on /mypage/page: /mypage, exiting the build.
49.92  ⨯ Static worker exited with code: 1 and signal: null
------
failed to solve: process "/bin/sh -c npm run build" did not complete successfully: exit code: 1
```

## 実装の際に参考にした資料等
問題となっている箇所のコードをCopilotに読み込ませ、原因分析や修正を実施しました。
AIの分析によると、「すべてのクライアントコンポーネントに"use client"という記述があるか確認する」「使用している関数がサーバーコンポーネントで使えるものであるか確認する」といった回答がなされ、それに沿って修正されたコードも出力されたため、内容を確認したうえでコードをコピペしたのですが、繰り返し、上記のようなエラーが出力され続けています。

## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
[メインリポジトリ](https://github.com/tokaisagami/nightmare-app/tree/main)
[フロントエンド(Next)](https://github.com/tokaisagami/nightmare-app-next)
[バックエンド](https://github.com/tokaisagami/nightmare-app-backend)　※バックエンドは今回のエラーに関係していませんが、一応連携しておきます。

## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
フロントエンド（nightmare-app-next）全体です。（あいまいで大変申し訳ございません。）

## 検証した結果から分かったこと・考えたこと
全てのクライアントコンポーネントをAIの指摘通りに修正しても、同じエラーが出力され続けていたため、nightmare-app-next/src/app配下のクライアントコンポーネント配下のファイルの記述の問題でないような気がしています。
nightmare-app-next/next.config.tsも確認してみたのですが、記述に問題はないように思います。

対象範囲が膨大かつ、原因部分が特定されていない状況で大変申し訳ないのですが、あれこれ試してみて、一向に進展がなく手づまりな状態のため、一刻も早く問題を解消したく思っております。
よろしくお願いいたします。

**Comment by ippei-shimizu** [comment]
本プロジェクトではNext.js 15を使用しているかと思います。
Next.js15のアップデートでNext.jsの仕様がいくつか変更になっている箇所があります。
そのため、Next.jsのドキュメントや記事を調べてみましょう。
Next.js15に関する情報は、ChatGPTでも追いきれていない場合があるため、ドキュメントと記事を調べてみることをおすすめします。

https://nextjs.org/blog/next-15
